id: PB24DB784
initial_creation_type: input
source_metadata:
  title: Trulshik Rinpoche Series
  language: en
  description: Texts by and about Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö ('khrul
    zhig ngag dbang chos kyi blo gros, 1924–2011), one of the teachers of His Holiness
    the Fourteenth Dalai Lama.
  volume:
    498bc096378c4f489d8a82e8e2a3d0f4:
      title: Advice for Retreat
      parent: Advice
    8d1b511d3e5b4362a0078e1817d0a723:
      title: Advice for Tenzin Jamchen
      parent: Advice
    426b8fd8f24043889615fa11df545b6d:
      title: Advice in Four Lines
      parent: Advice
    ded94e34c5fc45f18670720d1c202679:
      title: A Prayer for Translators
      parent: Aspiration Prayers
    244c5934d35346379c96a35ec9d2dc5e:
      title: A Prayer for the Spread of Kyabje Dilgo Khyentse Rinpoche’s Termas
      parent: Aspiration Prayers
    1bed6c87fdfe479f8ae5650537843f3a:
      title: Prayer of the View, Meditation and Conduct
      parent: Aspiration Prayers
    d4227c1df1234b5686478fc5451885aa:
      title: Profound Prayer of Aspiration
      parent: Aspiration Prayers
    28ebcb932e364cbda7229ed5650aaed8:
      title: 'The Quintessential Blessing: A Guru Yoga'
      parent: Guru Yoga
    c1f3b48168fe49e9b3554cb2c5c6ea47:
      title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong
        Trulshik Rinpoche, the Representative of Guru Rinpoche'
      parent: Long Life Prayers
    7a5a491a0d9e4cd6bb9d1437668a4eae:
      title: Long Life Prayer for Alak Zenkar Rinpoche
      parent: Long Life Prayers
    4291d10ddd8c4e11bccb058db835ce63:
      title: Long Life Prayer for Kyabje Dzarong Trulshik Rinpoche
      parent: Long Life Prayers
    9bd97c6d59f8466984ed2909c4e0b04f:
      title: Long Life Prayer for Lodi Gyari Rinpoche
      parent: Long Life Prayers
    d2e868e35cf14eeea7624bc31104dc13:
      title: Long Life Prayer for Mayum Tsering Wangmo
      parent: Long Life Prayers
    0df0d6a3ccdf4d7fbb2afb55e6ab7cb7:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Long Life Prayers
    bcd273784fe343149182ee4fa9fb9fe3:
      title: Prayer for the Long Life of Dilgo Khyentsé II of Shechen, Urgyen Tenzin
        Jigme Lhundrup
      parent: Long Life Prayers
    7ea1177b53af46b086729a4d8c704e3f:
      title: Prayer for the Long Life of His Holiness the Fourteenth Dalai Lama
      parent: Long Life Prayers
    83485bbee68e4629a6d99db63c88a379:
      title: Prayer for the Long Life of Sogyal Rinpoche—chimé kunnyé
      parent: Long Life Prayers
    7e9cab5a40b245e39e9e616130cc8cf9:
      title: Prayer for the Long Life of Sogyal Rinpoche—sönam jewé
      parent: Long Life Prayers
    92e5f4a0482e441ead359dfba7938a62:
      title: Prayer for the Long Life of Taklung Tsetrul Rinpoche
      parent: Long Life Prayers
    4f2110c0426c4a00b65107311368a350:
      title: The Attainment of Immortality
      parent: Long Life Prayers
    40e6c9462e6b4f86961c420022525fb1:
      title: A Homage to His Holiness the Dalai Lama
      parent: Praise
    d92e96ceccf44c19a466d1f4cf6ef89c:
      title: Verses of Homage
      parent: Praise
    f48dd885d3424b928175dfbd9803e44e:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: Praise
    e9630fb6f30b488a8abfd7f03ba22f6a:
      title: A Record of the Successive Incarnations
      parent: Prayers
    f0b5394c520345e9b3d024372dcbbfa4:
      title: 'Gateway for the Faithful: A Supplication Recalling the Lives and Liberation
        of Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö'
      parent: Prayers
    870887c6a4c24636b471da8d58a2ab73:
      title: A Brief Daily Practice of Damdrip Nyepa Kunsel
      parent: Sādhanas
    b4e33a4cfb27417f80a3aaa88843ac99:
      title: Prayer for the Swift Rebirth of Kyabjé Trulshik Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T01:52:59.286921'
last_modified_at: '2022-03-01T01:52:59.286929'
